name: Build Windows Executable

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-SDL2
            make

      # 3. 执行 Make 编译，Windows 编译器会自动生成 fshistory.exe
      - name: Build Windows Binary
        shell: msys2 {0}
        run: |
          make fshistory

      # 4. 直接上传生成的 fshistory.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fshistory-windows-executable
          path: fshistory.exe
